config/routes.rb
# frozen_string_literal: true
require 'sidekiq/web'
Rails.application.routes.draw do
  use_doorkeeper

  authenticate :user, ->(u) { u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  root to: 'questions#index'

  patch 'users/confirmation_email', to: 'users#confirmation_email', as: 'user_confirmation_email'

  concern :votable do
    resources :votes, only: [:create, :destroy]
  end

  concern :commentable do
    resources :comments, only: [:create]
  end

  resource :search, only: [:show]

  resources :questions, concerns: [:votable, :commentable] do
    resources :answers, concerns: [:votable, :commentable], shallow: true do
      member do
        patch :mark_best
      end
    end
    resources :subscriptions, only: [:create, :destroy], shallow: true
  end

  namespace :api do
    namespace :v1 do
      resource :profiles do
        get :me, on: :collection
        get :index
      end
      resources :questions do
        resources :answers, shallow: true
      end
    end
  end

  resources :attachments, only: [:destroy]
  mount ActionCable.server => '/cable'
end

app/models/question.rb
# frozen_string_literal: true
class Question < ApplicationRecord
  include HasUser
  include Attachable
  include Votable
  include Commentable
  has_many :answers, dependent: :destroy
  has_many :subscriptions, dependent: :destroy

  validates :title, :body, presence: true, length: { minimum: 10 }

  scope :lastday, -> { where(created_at: 1.day.ago..Time.current) }

  after_create :subscribe

  private

  def subscribe
    subscriptions.create(user_id: user_id)
  end
end

app/controllers/api/v1/questions_controller.rb
# frozen_string_literal: true
class Api::V1::QuestionsController < Api::V1::BaseController
  before_action :set_question, only: [:show]

  authorize_resource

  def index
    @questions = Question.all
    respond_with(@questions, each_serializer: QuestionsSerializer)
  end

  def show
    respond_with(@question)
  end

  def create
    @question = current_resource_owner.questions.create(question_params)
    respond_with(@question)
  end

  private

  def set_question
    @question = Question.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:title, :body)
  end
end

app/controllers/questions_controller.rb
# frozen_string_literal: true
class QuestionsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :load_question, only: [:show, :update, :destroy]
  before_action :build_answer, only: [:show]

  after_action :publish_question, only: [:create]

  authorize_resource

  respond_to :js, only: [:update]

  def index
    respond_with(@questions = Question.all)
  end

  def show
    respond_with(@question)
  end

  def new
    respond_with(@question = Question.new)
  end

  def create
    respond_with(@question = current_user.questions.create(question_params))
  end

  def update
    @question.update(question_params)
    respond_with(@question)
  end

  def destroy
    @question.destroy
    respond_with(@question)
  end

  private

  def load_question
    @question = Question.find(params[:id])
  end

  def build_answer
    @answer = @question.answers.build
  end

  def question_params
    params.require(:question).permit(:title, :body, attachments_attributes: [:file, :id, :_destroy])
  end

  def publish_question
    return if @question.errors.any?
    ActionCable.server.broadcast('questions', @question)
  end
end

app/helpers/questions_helper.rb
# frozen_string_literal: true
module QuestionsHelper
end

app/views/questions/_answer.html.slim
div class="answer"
  = answer.body
  - if user_signed_in? && current_user.author?(answer)
    div class="delete"
      = link_to t('answers.answer.destroy_answer'), answer, method: :delete

app/views/questions/_butn.html.slim
.container
  .row
    .col-lg-10.text-right
      - if can?(:create, Question)
        = link_to t('layouts.header.new_question'), new_question_path, class: 'btn btn-primary'

app/views/questions/_form_edit.html.slim
= form_for question, remote: true, html: {id: 'edit-question'} do |f|
  .question-errors
  = f.label :title
  p.control
    = f.text_field :title
  = f.label :body
  p.control
  = f.text_area :body
  = f.submit t('questions.show.save')

app/views/questions/_question.html.slim
section.hero
  .hero-body
    .container.question
      h2.title
        = @question.title
      = render 'votes/vote', entity: @question
      = @question.body
      .subscription
        = render 'subscriptions/subscription', question: @question
      = render 'attachments/attachments', entity: @question
      - if can?(:update, @question)
        div.question-edit
          = link_to t('questions.show.edit'), '', class: 'edit-question-link'
          = render 'form_edit', question: @question
      - if can?(:destroy, @question)
        div
          = link_to t('questions.show.destroy_question'), @question, method: :delete

      div class="comments comments-question-#{@question.id}"
        = render 'comments/show', commentable: @question

app/views/questions/index.html.slim
= render 'questions/butn'
ul.nav.nav-tabs.navbar-right
  li.active
    a data-toggle="tab" href="#home" Популярные вопросы
  li
    a data-toggle="tab" href="#menu1" Интересные
  li
    a data-toggle="tab" href="#menu2" Горячие
  li
    a data-toggle="tab" href="#menu2" Неделя
  li
    a data-toggle="tab" href="#menu2" Месяц
.tab-content
  #home.tab-pane.fade.in.active
    h3 Топ вопросов
  section.questions
    - @questions.each do |question|
      ul.list-group-item
        .table = link_to question.title, question
  #menu1.tab-pane.fade
    h3 Menu 1
    p Some content in menu 1.
  #menu2.tab-pane.fade
    h3 Menu 2
    p Some content in menu 2.

app/views/questions/new.html.slim
section.hero
  .hero-body
    .container
      h2.title
        | Add new question
      .columns
        .column.is-two-thirds
          = form_for @question do |f|
            = f.label :title
            p.control
              = f.text_field :title
            = f.label :body
            p.control
              = f.text_area :body
            = render 'attachments/form', f: f
            = f.submit t('helpers.label.question.create')

app/views/questions/show.html.slim
= render @question

section.answers *{'data-question-id'=>@question.id}
  = render @question.answers.first_best

- if user_signed_in?
  section.form_add_answer
    = render 'answers/form', question: @question, answer: @answer

app/views/questions/update.js.erb
$('.question-errors').html('');
<% if @question.errors.present? %>
  <% @question.errors.full_messages.each do |message| %>
      $('.question-errors').append('<span><%= j message %></span>');
  <% end %>
<% else %>
  $('.question').html('<%= j render @question %>');
<% end %>