config/routes.rb
# frozen_string_literal: true
require 'sidekiq/web'
Rails.application.routes.draw do
  use_doorkeeper

  authenticate :user, ->(u) { u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  root to: 'questions#index'

  patch 'users/confirmation_email', to: 'users#confirmation_email', as: 'user_confirmation_email'

  concern :votable do
    resources :votes, only: [:create, :destroy]
  end

  concern :commentable do
    resources :comments, only: [:create]
  end

  resource :search, only: [:show]

  resources :questions, concerns: [:votable, :commentable] do
    resources :answers, concerns: [:votable, :commentable], shallow: true do
      member do
        patch :mark_best
      end
    end
    resources :subscriptions, only: [:create, :destroy], shallow: true
  end

  namespace :api do
    namespace :v1 do
      resource :profiles do
        get :me, on: :collection
        get :index
      end
      resources :questions do
        resources :answers, shallow: true
      end
    end
  end

  resources :attachments, only: [:destroy]
  mount ActionCable.server => '/cable'
end

app/models/answer.rb
# frozen_string_literal: true
class Answer < ApplicationRecord
  include HasUser
  include Attachable
  include Votable
  include Commentable
  belongs_to :question

  validates :body, :question, presence: true, length: { minimum: 10 }

  scope :first_best, -> { order('best DESC') }

  after_create :notify

  def mark_best
    ActiveRecord::Base.transaction do
      question.answers.where(best: true).find_each { |answer| answer.update!(best: false) }
      update!(best: true)
    end
  end

  private

  def notify
    SubscriptionQuestionJob.perform_later(self)
  end
end

app/controllers/answers_controller.rb
# frozen_string_literal: true
class AnswersController < ApplicationController
  before_action :authenticate_user!, only: [:create, :destroy, :update, :mark_best]
  before_action :set_answer, only: [:update, :destroy, :mark_best]
  before_action :set_question, only: [:create]

  after_action :publish_answer, only: [:create]

  authorize_resource

  respond_to :js

  def create
    respond_with(@answer = @question.answers.create(answer_params.merge(user_id: current_user.id)))
  end

  def mark_best
    @answer.mark_best if current_user.author?(@answer.question)
    respond_with(@answer)
  end

  def update
    @answer.update(answer_params)
    respond_with(@answer)
  end

  def destroy
    @answer.destroy if current_user.author?(@answer)
    respond_with(@answer)
  end

  private

  def set_question
    @question = Question.find(params[:question_id])
  end

  def set_answer
    @answer = Answer.find(params[:id])
  end

  def answer_params
    params.require(:answer).permit(:body, attachments_attributes: [:file, :id, :_destroy])
  end

  def publish_answer
    return if @answer.errors.any?
    ActionCable.server.broadcast(
      "question_#{@question.id}_answers",
      answer: @answer,
      question_author: @answer.question.user.id,
      attachments: @answer.attachments.map { |a| { id: a.id, file_name: a.file.identifier, file_url: a.file.url } }
    )
  end
end

app/controllers/api/v1/answers_controller.rb
# frozen_string_literal: true
class Api::V1::AnswersController < Api::V1::BaseController
  before_action :set_question, only: [:index, :create]
  before_action :set_answer, only: [:show]

  authorize_resource

  def index
    @answers = @question.answers
    respond_with(@answers, each_serializer: AnswersSerializer)
  end

  def show
    respond_with(@answer)
  end

  def create
    @answer = @question.answers.create(answer_params.merge(user_id: current_resource_owner.id))
    respond_with(@answer)
  end

  private

  def set_answer
    @answer = Answer.find(params[:id])
  end

  def set_question
    @question = Question.find(params[:question_id])
  end

  def answer_params
    params.require(:answer).permit(:body)
  end
end

app/helpers/answers_helper.rb
# frozen_string_literal: true
module AnswersHelper
end

app/views/answers/_answer.html.slim
- if answer.persisted?
  div class=["answer", "answer-#{answer.id}"]
    .answer-best
      - if answer.best?
        b = t('answers.answer.best')
      - elsif can?(:mark_best, answer)
        = link_to t('answers.answer.best_up'), mark_best_answer_path(answer), method: :patch, remote: true
      = render 'votes/vote', entity: answer
      = answer.body
      = render 'attachments/attachments', entity: answer
      - if can?(:update, answer)
        = render 'answers/form_edit', answer: answer
      - if can?(:destroy, answer)
        = link_to t('answers.answer.destroy_answer'), answer, method: :delete, data: { confirm: 'The answer will be deleted. You are sure?' }, remote: true
      div class=["comments", "comments-answer-#{answer.id}"]
        = render 'comments/show', commentable: answer
      hr

app/views/answers/_form.hrml.slim
= form_for [question, question.answers.build] do |f|
  = f.label :body
  br
  = f.text_area :body
  br
  = f.submit 'Add new answer'

app/views/answers/_form.html.slim
= form_for [question, question.answers.build], remote: true do |f|
  = f.label :body, t('answers.answer.body_answer')
  br
  .answer-errors
  = f.text_area :body
  br
  = render 'attachments/form', f: f
  = f.submit t('shared.answer_form.asked')

app/views/answers/_form_edit.html.slim
div
  = link_to t('answers.answer.edit'), '', class: 'edit-answer-link', data: { answer_id: answer.id }
div.answer-edit
  = form_for answer, remote: true, html: { id: "edit-answer-#{answer.id}" } do |f|
    = f.label :body, t('answers.answer.body_answer')
    = f.text_area :body, id: "body-answer-#{answer.id}"
    = f.submit t('answers.answer.save')

app/views/answers/create.js.erb
$('.answer-errors').html('');
<% if @answer.errors.present? %>
  <% @answer.errors.full_messages.each do |message| %>
      $('.answer-errors').append('<span><%= j message %></span>');
    <% end %>
<% else %>
  $('.answers').append('<%= j render @answer %>');
  $('#answer_body').val('');
<% end %>

app/views/answers/destroy.js.erb
<% if @answer.destroyed? %>
  $('.answer-<%= @answer.id %>').remove();
  $('.notice').html('Ваш ответ был успешно удален.');
<% else %>
  $('.alert').html('Вы не можете удалить ответ!');
<% end %>

app/views/answers/mark_best.js.erb
$('.answers').html('<%= j render @answer.question.answers.first_best %>');

app/views/answers/update.js.erb
$('.answer-errors').html('');
<% if @answer.errors.present? %>
  <% @answer.errors.full_messages.each do |message| %>
    $('.answer-errors').append('<span><%= j message %></span>');
  <% end %>
<% else %>
  $('.answer-<%= @answer.id %>').html('<%= j render @answer %>');
<% end %>