config/routes.rb
# frozen_string_literal: true
require 'sidekiq/web'
Rails.application.routes.draw do
  use_doorkeeper

  authenticate :user, ->(u) { u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  root to: 'questions#index'

  patch 'users/confirmation_email', to: 'users#confirmation_email', as: 'user_confirmation_email'

  concern :votable do
    resources :votes, only: [:create, :destroy]
  end

  concern :commentable do
    resources :comments, only: [:create]
  end

  resource :search, only: [:show]

  resources :questions, concerns: [:votable, :commentable] do
    resources :answers, concerns: [:votable, :commentable], shallow: true do
      member do
        patch :mark_best
      end
    end
    resources :subscriptions, only: [:create, :destroy], shallow: true
  end

  namespace :api do
    namespace :v1 do
      resource :profiles do
        get :me, on: :collection
        get :index
      end
      resources :questions do
        resources :answers, shallow: true
      end
    end
  end

  resources :attachments, only: [:destroy]
  mount ActionCable.server => '/cable'
end

app/models/subscription.rb
# frozen_string_literal: true
class Subscription < ApplicationRecord
  belongs_to :user
  belongs_to :question
end

app/controllers/subscriptions_controller.rb
# frozen_string_literal: true
class SubscriptionsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_question, only: [:create]
  before_action :set_subscription, only: [:destroy]

  authorize_resource

  respond_to :js

  def create
    @subscription = @question.subscriptions.new(user: current_user)
    authorize! :create, @subscription
    @subscription.save
    respond_with(@subscription)
  end

  def destroy
    @subscription.destroy
    respond_with(@subscription)
  end

  private

  def set_question
    @question = Question.find(params[:question_id])
  end

  def set_subscription
    @subscription = Subscription.find(params[:id])
  end
end

app/helpers/subscriptions_helper.rb
# frozen_string_literal: true
module SubscriptionsHelper
  def user_can_unsubscribe?(entity)
    user_signed_in? && user_subscription(entity).present? && can?(:destroy, user_subscription(entity))
  end

  def user_subscription(entity)
    entity.subscriptions.find_by(user: current_user)
  end
end

app/views/subscriptions/_subscription.html.slim
- if can?(:create, question.subscriptions.build)
  = link_to 'Subscribe', question_subscriptions_path(question), method: :post, remote: true
- if user_can_unsubscribe?(question)
  = link_to 'Unsubscribe', user_subscription(question), method: :delete, remote: true

app/views/subscriptions/create.js.erb
<% unless @subscription.errors.present? %>
  $('.subscription').html('<%= j render 'subscriptions/subscription', question: @question %>')
<% end %>

app/views/subscriptions/destroy.js.erb
<% if @subscription.destroyed? %>
  $('.subscription').html('<%= j render 'subscriptions/subscription', question: @subscription.question %>')
<% end %>