config/routes.rb
# frozen_string_literal: true
require 'sidekiq/web'
Rails.application.routes.draw do
  use_doorkeeper

  authenticate :user, ->(u) { u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  root to: 'questions#index'

  patch 'users/confirmation_email', to: 'users#confirmation_email', as: 'user_confirmation_email'

  concern :votable do
    resources :votes, only: [:create, :destroy]
  end

  concern :commentable do
    resources :comments, only: [:create]
  end

  resource :search, only: [:show]

  resources :questions, concerns: [:votable, :commentable] do
    resources :answers, concerns: [:votable, :commentable], shallow: true do
      member do
        patch :mark_best
      end
    end
    resources :subscriptions, only: [:create, :destroy], shallow: true
  end

  namespace :api do
    namespace :v1 do
      resource :profiles do
        get :me, on: :collection
        get :index
      end
      resources :questions do
        resources :answers, shallow: true
      end
    end
  end

  resources :attachments, only: [:destroy]
  mount ActionCable.server => '/cable'
end

app/models/search.rb
class Search
  TYPES = %w(question answer comment user all).freeze
  PER_PAGE = 5

  def self.do(params = {})
    query = ThinkingSphinx::Query.escape(params[:q])
    options = {
        page: params[:page].nil? ? 1 : params[:page],
        per_page: params[:per_page].nil? ? PER_PAGE : params[:per_page]
    }
    unless params[:scopes].nil? || params[:scopes].include?('all')
      classes = params[:scopes].reject { |scope| scope unless TYPES.include?(scope) }
      classes.map! { |c| c.classify.constantize }
      options[:classes] = classes if classes.present?
    end
    ThinkingSphinx.search(query, options)
  end
end

app/controllers/searches_controller.rb
# frozen_string_literal: true
class SearchesController < ApplicationController
  def show
    if search_params.present?
      @result = Search.do(search_params)
      respond_with(@result)
    end
  end

  private

  def search_params
    params.permit(:q, :page, :per_page, scopes: [])
  end
end

app/helpers/searches_helper.rb
# frozen_string_literal: true
module SearchesHelper
end

app/views/searches/_answer.html.slim
.item.answer
  h3
    = link_to "Answer for question #{item.question.title}", question_path(item.question)
  div
    = item.body

app/views/searches/_comment.html.slim
.item.comment
  h3
    - if item.commentable_type == 'Question'
      = link_to "Comment for question #{item.commentable.title}", question_path(item.commentable)
    - else
      = link_to "Comment for answer question #{item.commentable.question.title}", question_path(item.commentable.question)
  div
    = item.content

app/views/searches/_form.html.slim
.search-form
  = form_tag search_path, method: :get
    = label_tag :q, 'text', class: 'label'
    .control
      = text_field_tag :q, params[:q], class: 'input'
    = label_tag :scopes, 'search in:', class: 'label'
    - Search::TYPES.each do|scope|
      .checkbox
        = check_box_tag 'scopes[]', scope, params[scope], id: "scope_#{scope}"
        = label_tag "scope_#{scope}", "in #{scope}", class: 'label'
    .field
      = submit_tag 'Search', class: 'button is-primary'

app/views/searches/_question.html.slim
.item.question
  h3
    = link_to item.title, question_path(item)
  div
    = item.body

app/views/searches/_result.html.slim
h3 Result
- if @result.empty?
  p Nothing found
- else
  - @result.each do |item|
    = render "#{item.model_name.to_s.underscore}", item: item
  = will_paginate @result

app/views/searches/_user.html.slim
.item.user
  = item.email

app/views/searches/show.html.slim
.section.search
  h2 Search
  = render 'form'
  - if @result
    .search-results
      = render 'result'